// GENERATED by build.py from swahili_wordscapes_levels_1-30.csv — do not edit by hand.
// Re-run `python3 build.py` to regenerate. Embedded (not fetched) so the game
// works offline and from file://.
const PUZZLES = [
  {"levelId": 1, "checkpoint": "Kituo cha Kati", "difficulty": "easy", "letters": ["A", "I", "L"], "base": "LIA", "answers": ["LIA", "ILA"], "bonusWords": []},
  {"levelId": 2, "checkpoint": "Nyayo", "difficulty": "easy", "letters": ["A", "O", "T"], "base": "TOA", "answers": ["TOA", "OTA", "OA"], "bonusWords": []},
  {"levelId": 3, "checkpoint": "Cabanas", "difficulty": "easy", "letters": ["A", "B", "I", "M"], "base": "IMBA", "answers": ["IMBA", "BIMA"], "bonusWords": ["MIA"]},
  {"levelId": 4, "checkpoint": "Athi River", "difficulty": "easy", "letters": ["A", "I", "J", "N"], "base": "JINA", "answers": ["JINA", "JANI", "NJIA", "NIA"], "bonusWords": []},
  {"levelId": 5, "checkpoint": "Mlolongo", "difficulty": "medium", "letters": ["A", "A", "K", "P"], "base": "PAKA", "answers": ["PAKA", "KAA", "APA", "PAA"], "bonusWords": []},
  {"levelId": 6, "checkpoint": "Kitengela", "difficulty": "medium", "letters": ["A", "A", "K", "T"], "base": "KATA", "answers": ["KATA", "TAKA", "KAA", "TAA"], "bonusWords": []},
  {"levelId": 7, "checkpoint": "Konza", "difficulty": "medium", "letters": ["A", "A", "P", "T"], "base": "PATA", "answers": ["PATA", "PAA", "TAA", "APA"], "bonusWords": []},
  {"levelId": 8, "checkpoint": "Malili", "difficulty": "medium", "letters": ["A", "I", "L", "M"], "base": "LIMA", "answers": ["LIMA", "MILA", "MALI", "LAMI", "ILA"], "bonusWords": ["LIA", "MIA"]},
  {"levelId": 9, "checkpoint": "Machakos Junction", "difficulty": "hard", "letters": ["A", "E", "K", "M", "T"], "base": "MKATE", "answers": ["MKATE", "MATE", "TEMA", "META", "MKE", "TEKA"], "bonusWords": []},
  {"levelId": 10, "checkpoint": "Salama", "difficulty": "hard", "letters": ["A", "A", "B", "R", "U"], "base": "BARUA", "answers": ["BARUA", "BARA", "BURA", "BAA", "RABA", "UA", "AU"], "bonusWords": []},
  {"levelId": 11, "checkpoint": "Sultan Hamud", "difficulty": "hard", "letters": ["A", "B", "I", "K", "T", "U"], "base": "KITABU", "answers": ["KITABU", "KATI", "KITU", "TABU", "BAKI", "BATI", "TIA"], "bonusWords": ["AU", "TAI", "UA"]},
  {"levelId": 12, "checkpoint": "Kima", "difficulty": "hard", "letters": ["A", "A", "I", "K", "M", "S"], "base": "SAMAKI", "answers": ["SAMAKI", "AMKA", "KAMA", "KISA", "KASI", "SAA", "KIMA", "SAKA", "KASA"], "bonusWords": ["ASI", "KAA", "MIA"]},
  {"levelId": 13, "checkpoint": "Emali", "difficulty": "hard", "letters": ["A", "I", "K", "K", "P", "U"], "base": "KIKAPU", "answers": ["KIKAPU", "KAPU", "KIPA", "KAKI", "PIKA", "PUA"], "bonusWords": ["AU", "UA"]},
  {"levelId": 14, "checkpoint": "Makindu", "difficulty": "hard", "letters": ["A", "A", "G", "I", "M", "R"], "base": "MAGARI", "answers": ["MAGARI", "GARI", "MARA", "AMRI", "IMARA", "RAI", "AGA"], "bonusWords": ["MIA"]},
  {"levelId": 15, "checkpoint": "Kibwezi", "difficulty": "hard", "letters": ["A", "I", "K", "R", "S", "U"], "base": "SUKARI", "answers": ["SUKARI", "KISU", "KASI", "KISA", "KURA", "RUKA", "RASI"], "bonusWords": ["ASI", "AU", "RAI", "UA"]},
  {"levelId": 16, "checkpoint": "Mtito Andei", "difficulty": "hard", "letters": ["A", "A", "I", "K", "N", "S"], "base": "KANISA", "answers": ["KANISA", "KISA", "KINA", "SINA", "AINA", "KANA", "NASA", "SAKA", "KASA", "SAA"], "bonusWords": ["ASI", "KAA", "KASI", "NIA", "SANA"]},
  {"levelId": 17, "checkpoint": "Tsavo", "difficulty": "expert", "letters": ["A", "A", "D", "I", "K", "N", "T"], "base": "KITANDA", "answers": ["KITANDA", "KANDA", "TANDA", "KATA", "KATI", "KINA", "TAI", "NIA"], "bonusWords": ["ADA", "AINA", "KAA", "KADI", "KANA", "NATA", "TAA", "TAKA", "TIA"]},
  {"levelId": 18, "checkpoint": "Manyani", "difficulty": "expert", "letters": ["A", "A", "D", "M", "N", "T", "U"], "base": "MATUNDA", "answers": ["MATUNDA", "TUNDA", "TANDA", "DAMU", "DUMA", "MTU", "TUNA", "NATA"], "bonusWords": ["ADA", "AU", "MTAA", "TAA", "UA", "UMA"]},
  {"levelId": 19, "checkpoint": "Voi", "difficulty": "expert", "letters": ["A", "B", "I", "N", "S", "T", "U"], "base": "BUSTANI", "answers": ["BUSTANI", "BASI", "BATI", "BUNI", "SINA", "TUNA", "TABU", "ASI", "TIA"], "bonusWords": ["AU", "NIA", "SITA", "TAI", "UA"]},
  {"levelId": 20, "checkpoint": "Maungu", "difficulty": "expert", "letters": ["A", "A", "A", "B", "K", "M", "T"], "base": "MAKTABA", "answers": ["MAKTABA", "KAMATA", "TAMKA", "MAKAA", "KAMBA", "KATA", "TAKA", "BATA", "KAA", "TAA", "BAA"], "bonusWords": ["AMKA", "KAMA", "MTAA"]},
  {"levelId": 21, "checkpoint": "Mackinnon Road", "difficulty": "expert", "letters": ["A", "F", "I", "K", "R", "U"], "base": "KIFARU", "answers": ["KIFARU", "FIKA", "KURA", "RUKA", "RAI", "UFA"], "bonusWords": ["AU", "UA"]},
  {"levelId": 22, "checkpoint": "Samburu", "difficulty": "expert", "letters": ["A", "A", "K", "L", "M", "U"], "base": "KALAMU", "answers": ["KALAMU", "KULA", "KAMA", "AMKA", "KAA", "UMA"], "bonusWords": ["AU", "UA"]},
  {"levelId": 23, "checkpoint": "Mariakani", "difficulty": "expert", "letters": ["A", "A", "G", "I", "M", "N"], "base": "NGAMIA", "answers": ["NGAMIA", "AMANI", "AINA", "GANI", "MIA", "NIA"], "bonusWords": ["AGA", "ANGA"]},
  {"levelId": 24, "checkpoint": "Mazeras", "difficulty": "expert", "letters": ["A", "I", "M", "R", "S", "T"], "base": "MSTARI", "answers": ["MSTARI", "SITA", "AMRI", "TIA", "RAI", "ASI"], "bonusWords": ["MIA", "RASI", "TAI"]},
  {"levelId": 25, "checkpoint": "Miritini", "difficulty": "expert", "letters": ["A", "I", "I", "K", "M", "S"], "base": "KISIMA", "answers": ["KISIMA", "SIKIA", "KISIA", "KIMA", "KISA", "MIA"], "bonusWords": ["ASI", "KASI"]},
  {"levelId": 26, "checkpoint": "Changamwe", "difficulty": "expert", "letters": ["A", "A", "H", "I", "N", "S"], "base": "SAHANI", "answers": ["SAHANI", "HANA", "HISA", "SINA", "AINA", "SANA", "NASA"], "bonusWords": ["ASI", "NIA", "SAA"]},
  {"levelId": 27, "checkpoint": "Nyali", "difficulty": "expert", "letters": ["A", "B", "I", "K", "R", "U"], "base": "KARIBU", "answers": ["KARIBU", "KABURI", "BAKI", "BURA", "RUKA", "KURA", "RIBA"], "bonusWords": ["AU", "RAI", "UA"]},
  {"levelId": 28, "checkpoint": "Bamburi", "difficulty": "expert", "letters": ["A", "A", "G", "M", "N", "O", "T"], "base": "MATANGO", "answers": ["MATANGO", "TANGO", "TANGA", "ANGA", "MTAA", "TOA", "OTA"], "bonusWords": ["AGA", "NATA", "OA", "TAA"]},
  {"levelId": 29, "checkpoint": "Likoni", "difficulty": "expert", "letters": ["A", "F", "I", "I", "M", "R", "S"], "base": "MSAFIRI", "answers": ["MSAFIRI", "SIFA", "FISI", "AMRI", "MIA", "RAI", "ASI"], "bonusWords": ["RASI"]},
  {"levelId": 30, "checkpoint": "Mombasa", "difficulty": "expert", "letters": ["A", "A", "D", "I", "K", "R", "T"], "base": "DAKTARI", "answers": ["DAKTARI", "KATA", "TAKA", "KATI", "KADI", "DIRA", "TIA", "RAI", "KAA", "TAA", "ADA"], "bonusWords": ["TAI"]}
];
if (typeof module !== 'undefined') { module.exports = PUZZLES; }
